#!/usr/local/bin/lua

local name = "template"
local longname = "Template"
local font = nil
local resolution = {1024, 768}

local box2d = false

local gl_version_expected = 1.0

local f, e = loadfile("glorp/Den")
assert(f, e)
f{name = name, longname = longname, font = font, resolution = resolution, box2d = box2d, gl_version_expected = gl_version_expected, targets = {...}}
